// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgmAwFFmUV3TXc1p9J-JEIuFIFathssA',
    appId: '1:235986873598:web:75e16536e8a6b9a9b109af',
    messagingSenderId: '235986873598',
    projectId: 'bd-connectup',
    authDomain: 'bd-connectup.firebaseapp.com',
    storageBucket: 'bd-connectup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSUw5JzaB0GlzlLZJbaTfAJLRv5_QTpk',
    appId: '1:235986873598:android:0b4a6b388b52b1f8b109af',
    messagingSenderId: '235986873598',
    projectId: 'bd-connectup',
    storageBucket: 'bd-connectup.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSgmAwFFmUV3TXc1p9J-JEIuFIFathssA',
    appId: '1:235986873598:web:c5fd89e7ff6dddd1b109af',
    messagingSenderId: '235986873598',
    projectId: 'bd-connectup',
    authDomain: 'bd-connectup.firebaseapp.com',
    storageBucket: 'bd-connectup.firebasestorage.app',
  );
}
